### ISSUE TITLE
Gnome 46 not working

### ISSUE THREAD

**Issue by stouracp** [purejava/fedora-update#10]

**Comment by purejava** [comment]
I know. The [requirements for GNOME 46](https://gjs.guide/extensions/upgrading/gnome-shell-46.html) changed, so the extension needs to be updated.

**Comment by purejava** [comment]
I updated the extension and made it compatible to GNOME 46.

The new version was already reviewed by the GNOME dev and published as `v11`.

**Comment by stouracp** [comment]
Thank you, it works.
