### ISSUE TITLE
Switched Gnome-Terminal to Gnome-Console, but updates not possible.

### ISSUE THREAD

**Issue by DeN-AlB** [purejava/fedora-update#11]
I removed Gnome-Terminal and installed Gnome-Console. When trying to use "Update now" in extension, the error appears that the command was not found.

`gnome-terminal -- /bin/sh -c "sudo dnf upgrade; echo Done - Press enter to exit; read _"`

I changed `gnome-termnal` into `gnome-console` or `console`, but the error still appears. Any idea what could be the correct command now?

Thanks in advance!

**Comment by purejava** [comment]
The executable for Console is named `kgx`. Use this instead and it will work.

**Comment by DeN-AlB** [comment]
Thank you very much! It works. :+1:
