### ISSUE TITLE
Update check in days vs. hours

### ISSUE THREAD

**Issue by jhawkins002** [purejava/fedora-update#19]
This feature would be great for those of us who use update notifications not so much to know when they are released but more as a reminder to apply them in a particular cycle. 

Given the Arch philosophy - I understand why the parent this extension was forked from was originally designed to ping the user in a window of hours for changes, but for other distros such as Fedora allowing the extension's alert logic to serve more as a longer-term "heads-up" service makes much more sense for the respective release cycle(s) .

**Comment by purejava** [comment]
Thanks for elaborating. Unfortunately, I don't get the point you are suggesting.
The delay before the first update check is run as well as the delay between two checks for updates can be configured in the preferences.

There are use cases, where a short delay is preferred, so I tend to not change these settings from seconds and minutes to hours and days.

**Comment by jhawkins002** [comment]
Thanks for the response! I'm trying to let you know there are other use cases and user needs where days vs. minutes are helpful. :)
