### ISSUE TITLE
The updates pending menu does not open, when notebook was put to sleep before

### ISSUE THREAD

**Issue by mhagnumdw** [purejava/fedora-update#2]
Here:
![image](https://github.com/purejava/fedora-update/assets/17688846/643ec57b-6254-4b72-ae6e-fef216fc6269)

**Comment by purejava** [comment]
Hi, thanks for the report.

Can you provide some information on your setup?

What operating system and version are you using?
What desktop environment and version are you on?
Please provide the D-Bus variant and version that is installed.

Thanks.

**Comment by mhagnumdw** [comment]
Hi! Thank you for your attention.

Fedora 28 64 bits
Gnome 44.5
X11

> Please provide the D-Bus variant and version that is installed.

How can I obtain this information?

**Comment by purejava** [comment]
> > Please provide the D-Bus variant and version that is installed.
> 
> How can I obtain this information?

Together with the other info you provided, `pgrep -lf dbus` should suffice.

**Comment by mhagnumdw** [comment]
> Please provide the D-Bus variant and version that is installed.

```
dbus-daemon --version
D-Bus Message Bus Daemon 1.14.10
Copyright (C) 2002, 2003 Red Hat, Inc., CodeFactory AB, and others
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by purejava** [comment]
Thanks.

I installed a fresh Fedora 38 and switched to X11. I cannot reproduce this issue.

What you might do is, to log into your GNOME session and open a terminal right away, while the shell extension is fetching updates. In the opened terminal, issue the following command: `journalctl -f -o cat /usr/bin/gnome-shell`.

This follows and shows the logs of GNOME shell and so of **all** shell extensions also. Don't worry, if this looks like this:
```log
Object St.Button (0x559196193d70), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.Button (0x559196193d70), has been already disposed — impossible to set any property on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.Button (0x559196193d70), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.Button (0x559196193d70), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object St.Button (0x559196193d70), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Object .Gjs_ui_windowPreview_WindowPreview (0x559194bdebf0), has been already disposed — impossible to get any property from it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
JS ERROR: TypeError: this.window_container is null
hideOverlay@resource:///org/gnome/shell/ui/windowPreview.js:373:9
vfunc_leave_event/this._idleHideOverlayId<@resource:///org/gnome/shell/ui/windowPreview.js:572:26

Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Received error from D-Bus search provider firefox.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
g_settings_get_flags() called on key 'xwayland-allow-byte-swapped-clients' which is not associated with a flags type
```

See, if there are yellow logs from `update-extension@purejava.org`, which is this extension. There should be none. Otherwise, the logs may indicate, what's wrong.

**Comment by mhagnumdw** [comment]
> Click on the updates menu and try to open it. See, if there are yellow logs from `update-extension@purejava.org`, which is this extension. There should be none. Otherwise, the logs may indicate, what's wrong.

I did everything you said. I even deactivated and reactivated the extension, and nothing was printed in the log. See this other issue https://github.com/purejava/fedora-update/issues/3 that I haven't turned off my notebook in 5 days.

I searched all over `journalctl` for `update-extension@purejava.org`. Below the result:

<details>
  <summary>journalctl with update-extension@purejava.org</summary>
<code>
out 21 10:37:45 dwnote2 gnome-character[1453379]: JS LOG: Characters Application exiting
out 21 10:38:16 dwnote2 gnome-shell[2663]: Usage of object.actor is deprecated for NotificationBanner
                                           get@resource:///org/gnome/shell/ui/environment.js:388:29
                                           style@/home/mhagnumdw/.local/share/gnome-shell/extensions/gnome-compact-top-bar@metehan-arslan.github.io/extension.js:126:3
                                           _showNotification@resource:///org/gnome/shell/ui/messageTray.js:1232:43
                                           _updateState@resource:///org/gnome/shell/ui/messageTray.js:1185:26
                                           _onNotificationShow@resource:///org/gnome/shell/ui/messageTray.js:1047:14
                                           showNotification@resource:///org/gnome/shell/ui/messageTray.js:769:18
                                           processNotification@resource:///org/gnome/shell/ui/notificationDaemon.js:387:18
                                           _notifyForSource@resource:///org/gnome/shell/ui/notificationDaemon.js:288:16
                                           NotifyAsync@resource:///org/gnome/shell/ui/notificationDaemon.js:191:14
                                           _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
                                           _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
out 21 10:38:57 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff736df8d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:38:57 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:38:57 dwnote2 gnome-shell[2663]: #0   55ff7b632e48 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:38:57 dwnote2 gnome-shell[2663]: #1   55ff7b632d78 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:38:57 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:38:57 dwnote2 gnome-shell[2663]: #0   55ff7b632e48 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:38:57 dwnote2 gnome-shell[2663]: #1   55ff7b632d78 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:38:57 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:38:57 dwnote2 gnome-shell[2663]: #0   55ff7b632e48 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:38:57 dwnote2 gnome-shell[2663]: #1   55ff7b632d78 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:38:57 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:38:57 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff789a29c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:38:57 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:38:57 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff75aec130), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:38:57 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:00 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff736df8d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:00 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:00 dwnote2 gnome-shell[2663]: #0   55ff7b632e48 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:00 dwnote2 gnome-shell[2663]: #1   55ff7b632d78 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:00 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:00 dwnote2 gnome-shell[2663]: #0   55ff7b632e48 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:00 dwnote2 gnome-shell[2663]: #1   55ff7b632d78 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:00 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:00 dwnote2 gnome-shell[2663]: #0   55ff7b632d78 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:00 dwnote2 gnome-shell[2663]: #1   7fff9d930aa0 b   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:00 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:00 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff789a29c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:00 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:00 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff75aec130), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:00 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:06 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff736df8d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:06 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:06 dwnote2 gnome-shell[2663]: #0   55ff7b632d78 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:06 dwnote2 gnome-shell[2663]: #1   7fff9d930aa0 b   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:06 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:06 dwnote2 gnome-shell[2663]: #0   55ff7b632d78 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:06 dwnote2 gnome-shell[2663]: #1   7fff9d930aa0 b   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:06 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:06 dwnote2 gnome-shell[2663]: #0   7fff9d9303c0 b   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:06 dwnote2 gnome-shell[2663]: #1   7fff9d930aa0 b   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:06 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:06 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff789a29c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:06 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:06 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff75aec130), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:06 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:09 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff736df8d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:09 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:09 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:09 dwnote2 gnome-shell[2663]: #0   55ff76275e58 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:09 dwnote2 gnome-shell[2663]: #1   55ff76275d88 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:09 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:09 dwnote2 gnome-shell[2663]: #0   55ff76275e58 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:09 dwnote2 gnome-shell[2663]: #1   55ff76275d88 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:09 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:09 dwnote2 gnome-shell[2663]: #0   55ff76275e58 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:09 dwnote2 gnome-shell[2663]: #1   55ff76275d88 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:09 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff789a29c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:09 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:09 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff75aec130), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:09 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:40 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff736df8d0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:40 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:40 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:40 dwnote2 gnome-shell[2663]: #0   55ff75813ca8 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:40 dwnote2 gnome-shell[2663]: #1   55ff75813bd8 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:40 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:40 dwnote2 gnome-shell[2663]: #0   55ff75813ca8 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:40 dwnote2 gnome-shell[2663]: #1   55ff75813bd8 i   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:40 dwnote2 gnome-shell[2663]: == Stack trace for context 0x55ff6ed3ce50 ==
out 21 10:39:40 dwnote2 gnome-shell[2663]: #0   55ff75813bd8 i   /home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196 (21ef73414510 @ 70)
out 21 10:39:40 dwnote2 gnome-shell[2663]: #1   7fff9d930aa0 b   self-hosted:1121 (2579e2273f60 @ 463)
out 21 10:39:40 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff789a29c0), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:40 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:40 dwnote2 gnome-shell[2663]: Object St.Bin (0x55ff75aec130), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
out 21 10:39:40 dwnote2 gnome-shell[2663]: JS ERROR: TypeError: this.container.get_parent() is null
                                           _positionChanged@/home/mhagnumdw/.local/share/gnome-shell/extensions/update-extension@purejava.org/extension.js:196:19
out 21 10:39:47 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.BrowserConnector@10.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.Boxes.SearchProvider@217.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.Calculator.SearchProvider@202.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.Characters@223.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.Contacts.SearchProvider@217.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.Photos@454.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.Settings.SearchProvider@173.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.gnome.clocks@222.service.
out 21 10:41:19 dwnote2 systemd[2225]: Started dbus-:1.2-org.mozilla.firefox.SearchProvider@596.service.
</code>
</details>

**Comment by mhagnumdw** [comment]
I restarted the system just now, so the menu started to work:

![image](https://github.com/purejava/fedora-update/assets/17688846/fc41e86c-0f38-4af0-8269-5bbecabe34c5)

ps: there are no records in journalctl today for `update-extension@purejava.org`

**Comment by mhagnumdw** [comment]
The problem happened again.

This time I did the following: Alt F2 > r > Enter

Then the extension checked for updates and put the number of pending updates. Ok.

Meanwhile I monitored the log with `journalctl -f | grep -C 5 'update-extension@purejava.org'`, and no logs appeared.

**Comment by purejava** [comment]
> > Click on the updates menu and try to open it. See, if there are yellow logs from `update-extension@purejava.org`, which is this extension. There should be none. Otherwise, the logs may indicate, what's wrong.
> 
> I did everything you said. I even deactivated and reactivated the extension, and nothing was printed in the log. See this other issue #3 that I haven't turned off my notebook in 5 days.
> 

Instead of deactivating and reactivating an extension, the best way to do this is to disable all extensions at once and re-enable them with the top most switch:
![Bildschirmfoto vom 2023-10-24 18-23-46](https://github.com/purejava/fedora-update/assets/1822238/b55dbd2f-3570-4e0e-8a1f-c2c97da6078f)

This really resets an extension in opposite to just dis- and enable a single extension.

> I searched all over `journalctl` for `update-extension@purejava.org`. Below the result:
> journalctl with update-extension@purejava.org
>

Anyway. The log indicates, that the extension crashes on line 196:
https://github.com/purejava/fedora-update/blob/a88391eda287f4627ff6efd12b8caf5a7366c128/extension.js#L196

I suspect that there is interference with other extensions. Could you please deactivate all other extension and see whether the issue remains?

**Comment by mhagnumdw** [comment]
I performed the steps below in order:

Notebook running and extension working fine, so I put the notebook to sleep (suspend), came back from sleep, then the `XX updates pending` menu stopped working.

I disabled all extensions at once (top toggle) and reactivated them and the extension still had the problem.

I left only the `Fedora Linux Update Indicator` extension activated and the extension remained with the problem.

**(From now on only the `Fedora Linux Update Indicator` extension was enabled)**

I disabled all extensions at once (top toggle) and reactivated them and the extension still had the problem.

I clicked on the `Check now` menu, the extension really checked for updates, and the `XX updates pending` menu started working again.

I put the notebook to sleep (suspend), came back from sleep, then the `XX updates pending` menu stopped working again.

During all these steps nothing appeared in the log with `journalctl -f | grep -C 5 'update-extension@purejava.org'`

We noticed here that when the notebook comes back from sleep (suspend), the `XX updates pending` menu stops working.

**Comment by purejava** [comment]
Thanks for your tests, but for all related to hibernate, you should open a different issue.

Please, let's stay focused in this issue, if the updates pending menu opens or not.

Does this still happen?

**Comment by mhagnumdw** [comment]
> Thanks for your tests, but for all related to hibernate, you should open a different issue.

But the tests above were to try to make the updates pending menu stop working (not open) and it happened.

> Does this still happen?

Yes.

**Comment by purejava** [comment]
I won't be able to help you here as I do not have a Linux installed on a notebook, only VMs, where resume from suspend is not working.

**Comment by purejava** [comment]
We could try another approach.

Could you add the log statement in `extension.js` in your installed extension:
```javascript
  _checkAutoExpandList() {
    log('UPDATES_PENDING = ' + UPDATES_PENDING);
    if (this.menu.isOpen && UPDATES_PENDING > 0 && UPDATES_PENDING <= AUTO_EXPAND_LIST) {
      this.menuExpander.setSubmenuShown(true);
    } else {
      this.menuExpander.setSubmenuShown(false);
    }
  }
```
and set "Auto-expand updates list ..." to 0 in the extensions settings?

This method is responsible, whether the updates menu gets opened or not.

The value of the variable gets printed to the log. Maybe suspending sets the variable to 0 and prevents the updates menu from being opened.

**Comment by mhagnumdw** [comment]
The problem is not with the `_checkAutoExpandList()` function, although it only returns `true` always, the `updates pending` menu does not open.

Where in javascript is responsible for monitoring the click event on the `updates pending` menu?

Another way would be for me to debug the extension, but I really don't have time for that right now. I still have to figure out how to do it...

**Comment by mhagnumdw** [comment]
I thought it might be a Gnome bug with submenu that occurs after suspend... but the submenus in the extension https://extensions.gnome.org/extension/1460/vitals/ continue to work after suspend.

**Comment by mhagnumdw** [comment]
The bot is mistaken.
