### ISSUE TITLE
Fedora 41 + DNF 5

### ISSUE THREAD

**Issue by mhagnumdw** [purejava/fedora-update#23]
Up to Fedora 40, with DNF 4, the output looks like this:

```bash
$ /usr/bin/dnf check-update --refresh -yq
brave-browser.x86_64                                                                 1.71.121-1                                                                    brave-browser-rpm-release.s3.brave.com_x86_64_
code.x86_64                                                                          1.95.0-1730153639.el8                                                         code                                          
dkms.noarch                                                                          3.1.1-1.fc40                                                                  updates                                       
```

So the default command line in  `Command to check for packages updates` works:
```bash
/usr/bin/dnf check-update --refresh -yq | tail -n +2  | grep -E 'x86_64|i686|noarch|aarch64' | awk '{print $1,$2}'
```

As of Fedora 41, which uses DNF 5, the output is like this:

```bash
$ /usr/bin/dnf check-update --refresh -yq
warp-terminal.x86_64 v0.2024.10.29.08.02.stable_02-1 warpdotdev
```

The command line in `Command to check for packages updates` needs to be adjusted to:
```bash
/usr/bin/dnf check-update -yq | awk '{print $1,$2}'
```

Note: neither before nor after I saw the need for the filter `grep -E 'x86_64|i686|noarch|aarch64'`

Suggested change:

Suggest the `Command to check for packages updates` according to the Fedora version.

**Comment by purejava** [comment]
Thanks for bringing this up @mhagnumdw and the additional info on DNF 5.

I'll look into it.

**Comment by purejava** [comment]
I need your help here to get the point.

Besides the different output of dnf 5, where the columns are closer to each other, compared to dnf 4, the extension still works with Fedora 41 and dnf 5. The `awk` command parses both outputs correctly.

Even if an adjustment of the command line to check for updates would be necessary, this could be changed in the advanced settings of the extension.

So what is this issue about? Thanks.

**Comment by mhagnumdw** [comment]
`tail -n +2` causes the first line to be lost in dnf 5:

![image](https://github.com/user-attachments/assets/d57653d5-e596-4872-aeaf-728e9cdadb87)

The idea here would then be to simply suggest a default command line according to the system's dnf version or according to the Fedora version, even though the user can customize the command.

**Comment by purejava** [comment]
Done. Release v22 has already been published, that checks, whether dnf 4 or 5 is installed and configures the extension accordingly. This ensures a smooth transition from Fedora 40 to 41.

All extensions rely on certain versions of the GNOME shell, the underlying Fedora version is secondary:
https://github.com/purejava/fedora-update/blob/f503074be1b204b06a11442bb21ef1664c79386a/metadata.json#L4
