### ISSUE TITLE
Use run0 instead of sudo by default + misc stuff

### ISSUE THREAD

**Issue by AshtakaOOf** [purejava/fedora-update#26]
run0 is part of systemd 256 (available in fedora 41) and opens a gnome password prompt (which is cleaner and cooler) instead of letting the sudo password prompt in the terminal do it.

also some other things (misc stuff in the title):
- using `check-upgrade` as user does not cache the update in the same place as `dnf` executed as root
  - could be worth having a button to set up a polkit rule in the extension settings to have it execute as root without password
- the `check-update` compatibility alias should be replaced with `check-upgrade` itself (just a nitpick)

**Comment by purejava** [comment]
> run0 is part of systemd 256 (available in fedora 41) and opens a gnome password prompt (which is cleaner and cooler) instead of letting the sudo password prompt in the terminal do it.
> 

I agree. Nevertheless, when I release a new version of the extension with `run0` as the default setting, all extension users get their extensions updated, also the ones, that are not on Fedora 41 yet. For these, it would require to change the setting back to `sudo` in the preferences.

So as a solution I will commit the change, but wait a while with publishing it to have more people migrated to Fedora 41 in the meantime.

> also some other things (misc stuff in the title):
> 
> * using `check-upgrade` as user does not cache the update in the same place as `dnf` executed as root
>   
>   * could be worth having a button to set up a polkit rule in the extension settings to have it execute as root without password

I don't think that this is required, as the extension just needs to check for updates periodically and doing this in the users context is sufficient.

> * the `check-update` compatibility alias should be replaced with `check-upgrade` itself (just a nitpick)
>
I don't think that this is required either. According to the dnf man page, `check-upgrade` is just an alias for `check-update`.

**Comment by AshtakaOOf** [comment]
> also the ones, that are not on Fedora 41 yet. For these, it would require to change the setting back to sudo in the preferences.

If needed you could have the extension execute `systemctl --version` to see if the version is `256` or newer.

The other suggestions are mostly nitpicks with how this extension behaves, they are not a deal breaker at all.

Please do close this issue if you deem it complete. :D

**Comment by purejava** [comment]
> If needed you could have the extension execute `systemctl --version` to see if the version is `256` or newer.
> 

Yes, the extension does that already e.g. to find out, whether dnf 4 or 5 is installed, as the behavior of dnf changed with the update to version 5. This can be done, but ends up with doubling the need to have preferences configurable. When you look at the last release, this changed and now there are two configuration options for both dnf versions.

I do not want to do that for every option in the preferences.

> The other suggestions are mostly nitpicks with how this extension behaves, they are not a deal breaker at all.
> 
> Please do close this issue if you deem it complete. :D
>

I'll do so. Thanks for your suggestions and interest in this.
