### ISSUE TITLE
There are updates, but the extension does not show

### ISSUE THREAD

**Issue by mhagnumdw** [purejava/fedora-update#3]
## Does not show that there are pending updates:

![image](https://github.com/purejava/fedora-update/assets/17688846/fe6019c6-6cde-4200-a6f0-fdd2cdd67be9)

## `/usr/bin/dnf check-update --refresh -yq | tail -n +2  | grep -E 'x86_64|i686|noarch|aarch64' | awk '{print $1,$2}'`

![image](https://github.com/purejava/fedora-update/assets/17688846/6a0c932b-6442-4d08-8227-3fcc7a8b9e2b)

## Conf

![image](https://github.com/purejava/fedora-update/assets/17688846/3cfc7f79-6e17-44dc-8d47-c1b877ff7e77)

![image](https://github.com/purejava/fedora-update/assets/17688846/94a1e2a7-bc74-4728-8409-9b715d2960e8)

## uptime

`16:12:12 up 5 days,  7:18,  2 users,  load average: 2,19, 2,45, 2,26`

During this time I just put the machine to sleep. I don't know if this is relevant, but I thought about it.

## Versions
- Fedora 38 64 bits
- Gnome 44.5
- X11
- D-Bus Message Bus Daemon 1.14.10

**Comment by mhagnumdw** [comment]
After system restart:

![image](https://github.com/purejava/fedora-update/assets/17688846/5e8a40f6-7416-4a17-b201-01a68ee130db)

Then (as expected):

![image](https://github.com/purejava/fedora-update/assets/17688846/fd097db6-892f-42b6-b1e1-8f65db23c00a)

A `journalctl | grep -C 10 'update-extension@purejava.org'` has no log from today and I have restarted the notebook almost now. The last log you have is the one I showed in this comment (from a few days ago): https://github.com/purejava/fedora-update/issues/2#issuecomment-1775889547-permalink

**Comment by purejava** [comment]
Do I understand it right, that after a restart the extension is working, and you had your notebook in hibernate before?

Hibernate should not be a problem, but the extension could have been not initialized completely with the installations, which could have caused the trouble.

**Comment by mhagnumdw** [comment]
> Do I understand it right, that after a restart the extension is working, and you had your notebook in hibernate before?

It only worked after I restarted the operating system.

ps: later I will do what you asked for #2

**Comment by purejava** [comment]
I won't be able to help you here as I do not have a Linux installed on a notebook, only VMs, where resume from suspend is not working.
