### ISSUE TITLE
Icon does not go away after updates are installed

### ISSUE THREAD

**Issue by aldafu** [purejava/fedora-update#7]
I configured the extension to only show an icon when there are package updates. When I start the update through the extension it would be nice for the icon to go away once all updates are installed successfully.

**Comment by purejava** [comment]
To be sure I understand you correctly: you unchecked "Indicator > Always" visible in the basic settings, right?

Using this, the icon goes away, after the extension has checked for updates the next time.

Does this not feel right for you?
