### ISSUE TITLE
Add option to use a pill in the status menu

### ISSUE THREAD

**Issue by thyttan** [purejava/fedora-update#8]
Instead of the indicator in the top bar, I'd like it if it was a pill among the quick-toggle pills in the system menu.

Thank you for fedora-update!

**Comment by purejava** [comment]
Hey, thanks for the input and your interest in the extension!

Having the extension as a quick setting would make it necessary to open the system menu to see, whether updates are available or not. From my point of view, that wouldn't be an update indicator any more. Therefore, I close this feature request.
