### ISSUE TITLE
Manage flatpak updates

### ISSUE THREAD

**Issue by thyttan** [purejava/fedora-update#9]
I'd find it convenient if the extension could handle flatpak updates as well.

I guess it might be possible for the user to fit it in by modifying the commands in advanced settings. But I'm not sure myself how to make it happen.

Thanks again for fedora-update!

**Comment by purejava** [comment]
Hey, thanks for the input and your interest in the extension!

The whole extension is designed to work on one package manager or packages source, not on two or more. I'd consider a flatpak remote repository as another packages source.

So unfortunately, this is out of scope.

The extension has a built-in regular expression to process the output of the search for updates command, so solving this by the commands in the advanced settings does not work either.

You can use GNOME Software, that has the complete flatpak package management on board.
